# Generated by Django 4.2.20 on 2025-12-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_id", models.IntegerField(unique=True)),
                ("sleep_id", models.CharField(blank=True, max_length=50, null=True)),
                ("user_id", models.IntegerField()),
                ("score_state", models.CharField(max_length=50)),
                ("user_calibrating", models.BooleanField(default=False)),
                ("recovery_score", models.IntegerField(blank=True, null=True)),
                ("resting_heart_rate", models.IntegerField(blank=True, null=True)),
                ("hrv_rmssd_milli", models.FloatField(blank=True, null=True)),
                ("spo2_percentage", models.FloatField(blank=True, null=True)),
                ("skin_temp_celsius", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recoveries",
                        to="users.athleteprofile",
                    ),
                ),
            ],
        ),
    ]
