# Generated by Django 4.2.20 on 2025-12-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recovery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recovery",
            name="user_id",
        ),
    ]
