# Generated by Django 4.2.20 on 2025-12-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recovery", "0002_remove_recovery_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="recovery",
            name="is_cutting_weight",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="recovery",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="recovery",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
