# Generated by Django 4.2.20 on 2026-01-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workouts", "0002_workout_is_cutting_weight"),
        ("users", "0003_athleteprofile_is_in_training_camp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="The date this summary represents"),
                ),
                ("recovery_score", models.IntegerField(blank=True, null=True)),
                ("sleep_efficient_score", models.IntegerField(blank=True, null=True)),
                ("strain_score", models.FloatField(blank=True, null=True)),
                ("is_cutting_weight", models.BooleanField(default=False)),
                ("is_preparing_for_competition", models.BooleanField(default=False)),
                ("is_in_training_camp", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="users.athleteprofile",
                    ),
                ),
                (
                    "workouts",
                    models.ManyToManyField(
                        blank=True, related_name="days", to="workouts.workout"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("athlete", "date")},
            },
        ),
    ]
