# Generated by Django 4.2.20 on 2026-01-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="workouts",
        ),
    ]
