# Generated by Django 4.2.20 on 2026-01-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_athleteprofile_is_weight_cutting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whoop_id",
                    models.IntegerField(
                        help_text="Unique identifier for the cycle activity",
                        unique=True,
                    ),
                ),
                ("whoop_user_id", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("timezone_offset", models.CharField(max_length=10)),
                ("score_state", models.CharField(max_length=20)),
                (
                    "score",
                    models.JSONField(help_text="Nested score object from Whoop API"),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="users.athleteprofile",
                    ),
                ),
            ],
        ),
    ]
