# Generated by Django 4.2.20 on 2025-12-17 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sleep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whoop_id",
                    models.CharField(
                        help_text="Unique identifier for the sleep activity",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("whoop_user_id", models.IntegerField()),
                ("cycle_id", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("timezone_offset", models.CharField(max_length=10)),
                ("nap", models.BooleanField(default=False)),
                ("score_state", models.CharField(max_length=20)),
                (
                    "score",
                    models.JSONField(help_text="Nested score object from Whoop API"),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sleeps",
                        to="users.athleteprofile",
                    ),
                ),
            ],
        ),
    ]
