# Generated by Django 4.2.20 on 2025-12-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleep", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sleep",
            name="is_cutting_weight",
            field=models.BooleanField(default=False),
        ),
    ]
