# Generated by Django 4.2.20 on 2025-12-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="athleteprofile",
            name="is_weight_cutting",
            field=models.BooleanField(default=False),
        ),
    ]
