# Generated by Django 4.2.20 on 2026-01-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_athleteprofile_is_weight_cutting"),
    ]

    operations = [
        migrations.AddField(
            model_name="athleteprofile",
            name="is_in_training_camp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="athleteprofile",
            name="is_preparing_for_competition",
            field=models.BooleanField(default=False),
        ),
    ]
