# Generated by Django 4.2.20 on 2025-12-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whoop_id", models.CharField(max_length=50, unique=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "timezone_offset",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("sport_id", models.IntegerField(blank=True, null=True)),
                ("score_state", models.CharField(blank=True, max_length=20, null=True)),
                ("strain", models.FloatField(blank=True, null=True)),
                ("average_heart_rate", models.IntegerField(blank=True, null=True)),
                ("max_heart_rate", models.IntegerField(blank=True, null=True)),
                ("kilojoule", models.FloatField(blank=True, null=True)),
                ("percent_recorded", models.FloatField(blank=True, null=True)),
                ("distance_meter", models.FloatField(blank=True, null=True)),
                ("altitude_gain_meter", models.FloatField(blank=True, null=True)),
                ("altitude_change_meter", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="users.athleteprofile",
                    ),
                ),
            ],
        ),
    ]
