# Generated by Django 4.2.20 on 2026-01-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0002_remove_day_workouts"),
        ("workouts", "0002_workout_is_cutting_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workouts",
                to="daily.day",
            ),
        ),
    ]
