# Generated by Django 4.2.20 on 2026-01-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_workout_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="athlete_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="trainer_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
