# Generated by Django 4.2.20 on 2025-12-11 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("medical_history", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalhistory",
            name="notes",
        ),
        migrations.CreateModel(
            name="MedicalHistoryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("AI", "AI"), ("HUMAN", "Human")], max_length=10
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                (
                    "medical_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="medical_history.medicalhistory",
                    ),
                ),
            ],
        ),
    ]
